### ISSUE TITLE
add type for react element

### ISSUE THREAD

**Issue by isaacs** [tapjs/tap-yaml#2]
Oof, that's a lotta noise there:

```js
const t = getSomeReactElement({...props})
console.log(require('tap-yaml').stringify({t}))
```

```yaml
t:
  $$typeof: !sym/for Symbol.for(react.element)
  type: !function |-
    class Box extends _react.PureComponent {
      constructor() {
        super();
        this.nodeRef = _react.default.createRef();
      }

      render() {
        const _this$props = this.props,
              {
          children,
          unstable__transformChildren
        } = _this$props,
              style = _objectWithoutProperties(_this$props, ["children", "unstable__transformChildren"]);

        return _react.default.createElement("div", {
          ref: this.nodeRef,
          style: style,
          unstable__transformChildren: unstable__transformChildren
        }, children);
      }

      unstable__getComputedWidth() {
        return this.nodeRef.current.yogaNode.getComputedWidth();
      }

    }
  key: null
  ref: null
  props:
    flexDirection: column
    children:
      - $$typeof: !sym/for Symbol.for(react.element)
        type: !function |-
          ({ ok, name, skip, todo }) => !name ? '' : React.createElement(
            Box,
            null,
            React.createElement(StatusMark, { res: { ok, name, skip, todo } }),
            ' ' + name
          )
        key: null
        ref: null
        props:
          ok: true
          name: some-test.js
          skip: false
          todo: false
        _owner: null
        _store: {}
      - $$typeof: !sym/for Symbol.for(react.element)
        type: !function |-
          ({ ok, name, skip, todo }) => React.createElement(
            Box,
            null,
            React.createElement(Glyph, { ok, skip, todo }),
            name,
            React.createElement(Reason, { skip, todo })
          )
        key: null
        ref: null
        props:
          ok: true
          name: thing
          skip: false
          todo: false
        _owner: null
        _store: {}
      - " "
      - ""
      - ""
      - ""
    flexGrow: 0
    flexShrink: 1
  _owner: null
  _store: {}
```
